env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - plugin:json/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - json
  - '@typescript-eslint'
rules:
  react/react-in-jsx-scope:
    off
    # This check isn't needed since React doesn't have
    # to be in scope starting in version 17
